### ISSUE TITLE
BibEdit: Improve keyboard shortcut for autocompletion

### ISSUE THREAD

**Issue by audub** [tind/invenio#16]
From Alex via support: 

Can we simplify the keyboard shortcut? Currently ctrl+shift+a on Mac. Perhaps shift+a is sufficient?

Note: shift + a will lead to A, so we have to find another shortcut. But at least, on a Mac it would feel more "native" to use cmd + shift + a.

**Comment by PXke** [comment]
I am studying the problem though cmd seems a hell to use in Javascript. shift + A Is already used to do the capital "A"
I will investigate more for cmd. But if you see another combinaison you are welcome !

**Comment by nietzold** [comment]
For mac, perhaps shift-cmd+a is a lot better than shift+ctrl+a?

best regards
Alexander Nietzold
tlf: +47 926 42 726

**Comment by PXke** [comment]
ctrl + space ? anyone @tind/invenio

**Comment by audub** [comment]
ctrl + space is ok for me. Mac users always use cmd instead of ctrl (i.e. cmd+c, cmd+v for copy/paste). Cmd+space is default for search on mac, so that is no option. But very few of our users are using mac I think, so it is probably nothing to worry about.

**Comment by PXke** [comment]
Hm I will see if can split it in two ! but it seems a bit complicated

**Comment by nietzold** [comment]
Why does shift+a not work?

Do you realize that the shortcut for "saving" an edit in bibedit is shift+s?

Would make sense to have:
shift+s = save
shift+a=autosuggest

best regards
Alexander Nietzold
tlf: +47 926 42 726

**Comment by nietzold** [comment]
I guess the difference is that when you press shift+a, you are not actually
editing one fields as you are doing when you want an autosuggestion. Sorry,
I did not think of that before.

best regards
Alexander Nietzold
tlf: +47 926 42 726

**Comment by audub** [comment]
My opinion is to not use much time on a mac-specific shortcut.

**Comment by PXke** [comment]
Okay so ctrl+space doesn't work :(

**Comment by audub** [comment]
I dont think we should use more time on this. We can conclude that it will take some time to implement separate shortcuts for mac and windows. And ctrl+shift+a works ok on windows.

Is it ok for you @nietzold ?

**Comment by nietzold** [comment]
Just go with shift+cmd+a for mac. Makes it a lot easier than shift+ctrl+a :)

best regards
Alexander Nietzold
tlf: +47 926 42 726

**Comment by nietzold** [comment]
preferably cmd+shift+a for mac, and ctrl+shift+a for windows?

I agree, let's not spend more time on this.

best regards
Alexander Nietzold
tlf: +47 926 42 726
