### ISSUE TITLE
BibEdit: IE 9 no validation

### ISSUE THREAD

**Issue by audub** [tind/invenio#22]
From Kenneth via support: 

Alfia showed me today that they have problems with record editor in Internet Explorer 9. Sometimes when they have added a field, it does not work to press enter. This leads to that the field are not saved, so when she press submit the data are not stored in the marc record.

I guess it`s a javascript bug because it happens only in IE. They have no problems in chrome. As she menation below, it seems that the problem happens always for ISBN while for the other fields the error is less consistent. 

It is consistent for field 020, but seems to be inconsistent for other fields.

**Comment by audub** [comment]
I assigned it to you, @PXke. You have worked most on BibEdit lately. Hopefully you are able to debug quickly.

**Comment by PXke** [comment]
SHould be working now.
